name: Test
on: [push, pull_request, workflow_dispatch]
jobs:
  test:
    name: Test with Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: "1.18"
      - uses: actions/checkout@v3
      - run: |
          go test -race -covermode atomic -coverprofile=profile.cov ./...
      - uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
      - uses: codecov/codecov-action@v3
        with:
          files: ./profile.cov